-- Free Exploit Library Example
spawn(function()
   loadstring(game:HttpGet("https://pastebin.com/raw/MKc92Crw", true))()
end)

local tab1 = CreateTab("Test", true)
local button = MakeButton(tab1,"Button",function(button)
   print ("Hi")
end)
local toggle = MakeToggle(tab1,"Toggle",false,function(toggle)
   print(toggle.Text)
end)
local text = MakeLabel(tab1,"Gay label")
local box = MakeBox(tab1,"Text Box","Default text",function(box)
   print (box.Text)
end)
local dropdown = MakeDropdown(tab1,"Dropdown",{"Ok","Ok","Ok"},"Ok",function(dropdown)
   print (dropdown.Text)
end)

local tab2 = CreateTab("Test", false)
local button = MakeButton(tab2,"Button",function(button)
   print ("Hi")
end)
local toggle = MakeToggle(tab2,"Toggle",false,function(toggle)
   print(toggle.Text)
end)
local text = MakeLabel(tab2,"Gay label")
local box = MakeBox(tab2,"Text Box","Default text",function(box)
   print (box.Text)
end)
local dropdown = MakeDropdown(tab2,"Dropdown",{"Ok","Ok","Ok"},"Ok",function(dropdown)
   print (dropdown.Text)
end)

local tab3 = CreateTab("Test", false, Color3.new(0,.7,.5))
local button = MakeButton(tab3,"Button",function(button)
   print ("Hi")
end)
local toggle = MakeToggle(tab3,"Toggle",false,function(toggle)
   print(toggle.Text)
end)
local text = MakeLabel(tab3,"Gay label")
local box = MakeBox(tab3,"Text Box","Default text",function(box)
   print (box.Text)
end)
local dropdown = MakeDropdown(tab3,"Dropdown",{"Ok","Ok","Ok"},"Ok",function(dropdown)
   print (dropdown.Text)
end)
